---
title: "SIH"
output: html_document
date: "2026-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Packages

```{r}
library(DataExplorer)
library(arrow)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(knitr)
library(kableExtra)
```

##### Data

```{r}
SIH <- read_parquet("C:/Users/alyss/Desktop/Brasil/Analysis/dados_current - 2026-06-09/Dados/resultados/SIH/sih_iexo_sp_2014_2024.parquet")
```

#### Clean

```{r}
SIH_clean <- SIH |>
  select(N_AIH,
         MES_CMPT,
         ANO_CMPT,
         MUNIC_RES,
         COD_IDADE,
         IDADE,
         SEXO,
         RACA_COR,
         DIAG_PRINC,
         CID_MORTE,
         MORTE,
         DIAS_PERM)
```

## Using Consolidated for Analyses

*This dataset already has transformed variables from SIH*

```{r}
consolidada <- read_parquet("~/GitHub/intox_agro/resultados/base_consolidada_sp_2014_2024.parquet")
```

# Hospitalization per 100K

#### Missing

```{r}
plot_missing(consolidada[, c("taxa_hosp_100k")])
```

## Create Quartiles

```{r}
consolidada <- consolidada %>%
  group_by(ano) %>%
  mutate(
    taxa_hosp_100k_quartile =
      ntile(desc(taxa_hosp_100k), 4)
  ) %>%
  ungroup()
```

## Table

```{r}

poisoning_summary <- consolidada %>%
  select(
    ano,
    taxa_hosp_100k,
    taxa_hosp_100k_quartile
  ) %>%
  rename(
    value = taxa_hosp_100k,
    Quartile = taxa_hosp_100k_quartile
  ) %>%
  group_by(ano, Quartile) %>%
  summarise(
    n = n(),
    Median = median(value, na.rm = TRUE),
    Min = min(value, na.rm = TRUE),
    Max = max(value, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    Range = paste0(Min, "-", Max)
  ) %>%
  select(ano, Quartile, n, Median, Range)


poisoning_summary

#kable
poisoning_summary %>%
  arrange(ano, Quartile) %>%
  kable(
    digits = 2,
    col.names = c(
      "Year",
      "Quartile",
      "n",
      "Median Rate",
      "Range"
    ),
    caption = "Hospitalization Rate Quartiles by Year"
  ) %>%
  collapse_rows(columns = 1) %>%
  kable_styling(full_width = FALSE)
```

## Plot

```{r}
ggplot(poisoning_summary,
       aes(x = ano, y = Median, color = factor(Quartile))) +
  geom_line() +
  geom_point() +
  scale_x_continuous(
    breaks = unique(sort(poisoning_summary$ano))
  ) +
  theme_minimal()
```

## Normality

```{r}
ggplot(consolidada, aes(x = taxa_hosp_100k)) +
  geom_histogram(bins = 30) +
  theme_minimal()
```

# Case-fatality Rate per 100K

## Create rate

```{r}

consolidada <- consolidada %>%
  mutate(sih_cfr = (sih_n_obitos_hosp / sih_n_hosp) * 100)

```

### Missing

```{r}
plot_missing(consolidada[, c("sih_cfr")])
```

#### Create Quartiles

```{r}
consolidada <- consolidada %>%
  group_by(ano) %>%
  mutate(
    sih_cfr_quartile =
      ntile(desc(sih_cfr), 4)
  ) %>%
  ungroup()
```

## Table

```{r}
fatality_summary <- consolidada %>%
  select(
    ano,
    sih_cfr,
    sih_cfr_quartile
  ) %>%
  rename(
    value = sih_cfr,
    Quartile = sih_cfr_quartile
  ) %>%
  group_by(ano, Quartile) %>%
  summarise(
    n = n(),
    Median = median(value, na.rm = TRUE),
    Min = min(value, na.rm = TRUE),
    Max = max(value, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    Range = paste0(Min, "-", Max)
  ) %>%
  select(ano, Quartile, n, Median, Range)


poisoning_summary

#kable
fatality_summary %>%
  arrange(ano, Quartile) %>%
  kable(
    digits = 2,
    col.names = c(
      "Year",
      "Quartile",
      "n",
      "Median Rate",
      "Range"
    ),
    caption = "Case Fatality Rate Quartiles by Year"
  ) %>%
  collapse_rows(columns = 1) %>%
  kable_styling(full_width = FALSE)

```

### Plot

```{r}
ggplot(fatality_summary,
       aes(x = ano, y = Median, color = factor(Quartile))) +
  geom_line() +
  geom_point() +
  scale_x_continuous(
    breaks = unique(sort(fatality_summary$ano))
  ) +
  theme_minimal()
```

## Normality

```{r}
ggplot(consolidada, aes(x = sih_cfr)) +
  geom_histogram(bins = 30) +
  theme_minimal()
```
