---
title: "IPVS"
output:
  html_document: default
  pdf_document: default
date: "2026-06-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Packages

```{r}
library(arrow) 
library(readr) 
library(dplyr) 
library(ggplot2)
library(tidyr)
library(purrr)
library(knitr)
library(kableExtra)
```

##### Dataset

```{r}
ipvs <- read_parquet("~/GitHub/intox_agro/resultados/contextual/ipvs_municipios_sp.parquet")

```

### Missingness

```{r}
sum(is.na(ipvs))
```

#### Clean

```{r}
ipvs <- ipvs |>
  mutate(
    ipvs_low = 
      ipvs_pct_grupo1 + ipvs_pct_grupo2,
    ipvs_medium =
      ipvs_pct_grupo3 + ipvs_pct_grupo4,
    ipvs_high =
      ipvs_pct_grupo5 + ipvs_pct_grupo6)

```

## % Households with High Paulista Social Vulnerability Index

### Raw Frequency

```{r}
median(ipvs$ipvs_high)

mean(ipvs$ipvs_high)

```

#### Create Quartiles

```{r}

ipvs <- ipvs |>
  mutate(
    ipvs_high_quartile = ntile(desc(ipvs_high), 4))
```

### Table

```{r}

ipvs_summary <- ipvs |>
  group_by(ipvs_high_quartile) |>
  summarise(
    n = n(),
    pct = round(100 * n() / nrow(ipvs), 1),
    Median = median(ipvs_high, na.rm = TRUE),
    Min = min(ipvs_high, na.rm = TRUE),
    Max = max(ipvs_high, na.rm = TRUE),
    .groups = "drop") |>
  mutate(
    Variable = "% Households with High Paulista Social Vulnerability Index ",
    Range = paste0(round(Min, 2), "-", round(Max, 2)) ) |>
  rename(Quartile = ipvs_high_quartile) |>
  select(Variable, Quartile, n, pct, Median, Range)

#kable
ipvs_summary |>
  kable(
    digits = 1,
    caption = "Distribution of Municipalities by % Households with High Paulista Social Vulnerability Index",
    col.names = c(
      "% Households with High Paulista Social Vulnerability Index ",
      "Quartile",
      "n",
      "%",
      "Median (%)",
      "Range"
    )
  ) |>
  collapse_rows(columns = 1) |>
  kable_styling(full_width = FALSE)
```

### Plot

```{r}

ggplot(ipvs,
       aes(x = factor(ipvs_high_quartile),
           y = ipvs_high,
           fill = factor(ipvs_high_quartile))) +
  geom_boxplot() +
  labs(
    title = "% Households with High Paulista Social Vulnerability Index by Quartile",
    x = "Quartile",
    y = "% Households with High Paulista Social Vulnerability Index",
    fill = "Quartile"
  ) +
  theme_minimal()
```

### Normality

```{r}
ipvs_vars <- c("ipvs_low", "ipvs_medium", "ipvs_high")

ipvs %>%
  select(all_of(ipvs_vars)) %>%
  pivot_longer(
    cols = everything(),
    names_to = "ipvs",
    values_to = "value"
  ) %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 20) +
  facet_wrap(~ ipvs, scales = "free") +
  theme_minimal()
```
