---
title: "SIH"
output: html_document
date: "2026-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Packages

```{r}
library(DataExplorer)
library(arrow)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(knitr)
library(kableExtra)
```

##### Data

```{r}
SIH <- read_parquet("C:/Users/alyss/Desktop/Brasil/Analysis/dados_current - 2026-06-09/Dados/resultados/SIH/sih_iexo_sp_2014_2024.parquet")
```

#### Clean

```{r}
SIH_clean <- SIH |>
  select(N_AIH,
         MES_CMPT,
         ANO_CMPT,
         MUNIC_RES,
         COD_IDADE,
         IDADE,
         SEXO,
         RACA_COR,
         DIAG_PRINC,
         CID_MORTE,
         MORTE,
         DIAS_PERM)
```

## Using Consolidated for Analyses

*This dataset already has transformed variables from SIH*

```{r}
consolidada <- read_parquet("~/GitHub/intox_agro/resultados/base_consolidada_sp_2014_2024.parquet")

#subset
poisoning <- consolidada |>
  select(cod_ibge,
         ano,
         sih_n_hosp_0_14,
         sinan_n_notif_0_14,
         sim_n_obitos_0_14,
         taxa_hosp_0_14_100k,
         taxa_notif_0_14_100k,
         taxa_obitos_sim_0_14_100k,
         sih_n_obitos_hosp_0_14)
```

# Hospitalization per 100K

#### Missing

```{r}
plot_missing(poisoning[, c("taxa_hosp_0_14_100k")])
```

### Raw Frequency

```{r}
median(poisoning$taxa_hosp_0_14_100k)

mean(poisoning$taxa_hosp_0_14_100k)
```

#### Create Quartiles

```{r}
poisoning <- poisoning %>%
  group_by(ano) %>%
  mutate(
    taxa_hosp_0_14_100k_quartile =
      ntile(taxa_hosp_0_14_100k, 4)
  ) %>%
  ungroup()
```

## Table

```{r}

poisoning_summary <- poisoning %>%
  select(
    ano,
    taxa_hosp_0_14_100k,
    taxa_hosp_0_14_100k_quartile
  ) %>%
  rename(
    value = taxa_hosp_0_14_100k,
    Quartile = taxa_hosp_0_14_100k_quartile
  ) %>%
  group_by(ano, Quartile) %>%
  summarise(
    n = n(),
    Median = median(value, na.rm = TRUE),
    Min = min(value, na.rm = TRUE),
    Max = max(value, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    Range = paste0(Min, "-", Max)
  ) %>%
  select(ano, Quartile, n, Median, Range)


poisoning_summary

#kable
poisoning_summary %>%
  arrange(ano, Quartile) %>%
  kable(
    digits = 2,
    col.names = c(
      "Year",
      "Quartile",
      "n",
      "Median Rate",
      "Range"
    ),
    caption = "Hospitalization Rate Quartiles by Year"
  ) %>%
  collapse_rows(columns = 1) %>%
  kable_styling(full_width = FALSE)
```

## Plot

```{r}
ggplot(poisoning_summary,
       aes(x = ano, y = Median, color = factor(Quartile))) +
  geom_line() +
  geom_point() +
  scale_x_continuous(
    breaks = unique(sort(poisoning_summary$ano))
  ) +
  labs(
    title = "Hospitalization Rate Ages 0-14 years per 100K",
    x = "Year",
    y = "Median Hospitalization Rate per 100K",
    color = "Quartile"
  ) +
  theme_minimal()
```

## Ribbon Plot

```{r}

summary_quartile <- poisoning %>%
  group_by(ano, taxa_hosp_0_14_100k_quartile) %>%
  summarise(
    min = min(taxa_hosp_0_14_100k, na.rm = TRUE),
    median = median(taxa_hosp_0_14_100k, na.rm = TRUE),
    max = max(taxa_hosp_0_14_100k, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(summary_quartile,
       aes(x = ano,
           y = median,
           color = factor(taxa_hosp_0_14_100k_quartile),
           group = taxa_hosp_0_14_100k_quartile)) +
  geom_linerange(aes(ymin = min, ymax = max), alpha = 0.5) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_x_continuous(breaks = unique(summary_quartile$ano)) +
  labs(
    x = "Year",
    y = "Value",
    color = "Quartile"
  ) +
  theme_minimal()

ggplot(poisoning,
       aes(x = factor(ano),
           y = taxa_hosp_0_14_100k,
           fill = factor(taxa_hosp_0_14_100k_quartile))) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    x = "Year",
    y = "Value",
    fill = "Quartile"
  ) +
  theme_minimal()
```

## Extreme Values

```{r}
range(poisoning$taxa_hosp_0_14_100k, na.rm = TRUE)

consolidada %>%
  filter(taxa_hosp_0_14_100k > 100) %>%
  arrange(desc(taxa_hosp_0_14_100k)) %>%
  select(cod_ibge, ano, taxa_hosp_0_14_100k)


#table
poisoning %>%
  group_by(cod_ibge) %>%
  summarise(
    n_years_over_100 = sum(taxa_hosp_0_14_100k > 100, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  filter(n_years_over_100 > 0) %>%
  arrange(desc(n_years_over_100))
```

## Normality

```{r}
ggplot(poisoning, aes(x = taxa_hosp_0_14_100k)) +
  geom_histogram(bins = 30) +
  theme_minimal()
```

# Case-fatality Rate per 100K

## Create rate

```{r}

poisoning <- poisoning %>%
  mutate(
    sih_cfr = if_else(sih_n_hosp_0_14 > 0,
                      (sih_n_obitos_hosp_0_14 / sih_n_hosp_0_14) * 100,
                      NA_real_))
```

#### Missing

```{r}
plot_missing(poisoning[, c("sih_cfr")])
```

### Raw Frequency

```{r}
median(poisoning$sih_cfr, na.rm = TRUE)

mean(poisoning$sih_cfr, na.rm = TRUE)
```

#### Create Quartiles

```{r}
poisoning <- poisoning %>%
  group_by(ano) %>%
  mutate(
    sih_cfr_quartile =
      ntile(sih_cfr, 4)
  ) %>%
  ungroup()
```

## Table

```{r}
fatality_summary <- poisoning %>%
  select(
    ano,
    sih_cfr,
    sih_cfr_quartile
  ) %>%
  rename(
    value = sih_cfr,
    Quartile = sih_cfr_quartile
  ) %>%
  group_by(ano, Quartile) %>%
  summarise(
    n = n(),
    Median = median(value, na.rm = TRUE),
    Min = min(value, na.rm = TRUE),
    Max = max(value, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    Range = paste0(Min, "-", Max)
  ) %>%
  select(ano, Quartile, n, Median, Range)


fatality_summary

#kable
fatality_summary %>%
  arrange(ano, Quartile) %>%
  kable(
    digits = 2,
    col.names = c(
      "Year",
      "Quartile",
      "n",
      "Median Rate",
      "Range"
    ),
    caption = "Case Fatality Rate Quartiles by Year"
  ) %>%
  collapse_rows(columns = 1) %>%
  kable_styling(full_width = FALSE)

```

### Plot

```{r}
ggplot(fatality_summary,
       aes(x = ano, y = Median, color = factor(Quartile))) +
  geom_line() +
  geom_point() +
  scale_x_continuous(
    breaks = unique(sort(fatality_summary$ano))
  ) +
  theme_minimal()
```

## Normality

```{r}
ggplot(poisoning, aes(x = sih_cfr)) +
  geom_histogram(bins = 30) +
  theme_minimal()
```

#### Save dataset for mapping

```{r}

for (yr in 2014:2024) {
  poisoning %>%
    filter(ano == yr) %>%
    write_csv(paste0("poisoning_", yr, ".csv"))
}

```
